---
- name: EC2 Playbook
  hosts: all
  become: true

  tasks:
  - name: Disable Docker Service
    service:
        name: docker
        enabled: false
        state: stopped

  - name: Install Apache httpd
    yum:
      name: httpd
      state: latest

  - name: Start Apache httpd
    service:
      name: httpd
      enabled: true
      state: started

  - name: Install App
    copy: ../hello-2048/public_html/
    dest: /var/www/html/
    owner: apache
    group: apache
    mode: "0644"
    directory_mode: "0755"


